### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by redsn0w422** [HackIllinois/blog#11]

**Comment by justinyangusa** [comment]
@ASankaran are you planning on working on this? If not, I can look into it.

**Comment by ASankaran** [comment]
Sorry, took a bit of time to get around to this. I had the analytics added (just pushed that branch), but I we need to generate our tracking code. Not sure which account we want that to be generated from. Once the code is generated though it just need to be added [here](https://github.com/HackIllinois/blog/blob/f5154d5843d0c22b5cefb71212c9f49d6aaace30/_config.yml#L34).
