### ISSUE TITLE
Add CODEOWNERS to blog

### ISSUE THREAD

**Issue by redsn0w422** [HackIllinois/blog#31]
We should add CODEOWNERS to the blog repo with @smg155 and @apa-123 so that all PRs have to be approved by both of them before merging.

**Comment by ASankaran** [comment]
Currently approving PRs into master are restricted to only organization and repository admins (which includes @smg155 and @apa-123). This is the most restrictive setting GitHub allows, since admins always have permissions to force override restrictions.
